In [16]:
import numpy as np
import pprint 

In [17]:
# tran = np.array()
# l1=input("Enter the number of websites")
l1=4

In [18]:
# for i in range(l1):
#     for j in range(l1):
#         tran[i][j] = input("Enter link of node")
#taking in adjacency matrix        

In [19]:
# tran.reshape(l1,l1)

In [20]:
pp=pprint.PrettyPrinter(indent=4)

In [21]:
#pagerank algorithm

In [22]:
tran=np.array([[0.,1.,1.,1.],[0.,0.,1.,1.],[1.,0.,0.,0.],[1.,0.,1.,0.]])

In [23]:
for numb,i in enumerate(tran):
    norm=np.sum(i)
    if norm!=0:
        tran[numb]=np.true_divide(i,norm)

In [24]:
tran=np.transpose(tran)
pp.pprint(tran)

array([[0.        , 0.        , 1.        , 0.5       ],
       [0.33333333, 0.        , 0.        , 0.        ],
       [0.33333333, 0.5       , 0.        , 0.5       ],
       [0.33333333, 0.5       , 0.        , 0.        ]])


In [25]:
initial_rank = 1./l1

In [26]:
rank=np.ones(4) * initial_rank

In [27]:
pp.pprint(rank)

array([0.25, 0.25, 0.25, 0.25])


In [28]:
iter_num = 6 # the number of iterations we are going for

In [29]:
for i in range(iter_num):
    rank=np.matmul(tran,rank)

In [30]:
pp.pprint(rank)

array([0.38194444, 0.13020833, 0.29166667, 0.19618056])
